import { 
  FileText, 
  List, 
  Quote, 
  Image, 
  Video, 
  Link, 
  Heading1, 
  Heading2, 
  Code, 
  Table, 
  Minus,
  Square,
  Layers,
  Music,
  FileText as Document
} from 'lucide-react';
import type { ElementType } from '../../types/project';

export const elementTypeIcons: Record<ElementType, typeof FileText> = {
  document: Document,
  section: Heading1,
  chapter: Heading2,
  scene: FileText,
  paragraph: FileText,
  list: List,
  quote: Quote,
  image: Image,
  video: Video,
  link: Link,
  code: Code,
  table: Table,
  divider: Minus,
  canvas: Square,
  card: Layers,
  audio: Music,
};

export const elementTypeLabels: Record<ElementType, string> = {
  document: 'Document',
  section: 'Section',
  chapter: 'Chapter',
  scene: 'Scene',
  paragraph: 'Paragraph',
  list: 'List',
  quote: 'Quote',
  image: 'Image',
  video: 'Video',
  link: 'Link',
  code: 'Code',
  table: 'Table',
  divider: 'Divider',
  canvas: 'Canvas',
  card: 'Card',
  audio: 'Audio',
};

export const elementTypeColors: Record<ElementType, string> = {
  document: 'bg-blue-500',
  section: 'bg-purple-500',
  chapter: 'bg-indigo-500',
  scene: 'bg-violet-500',
  paragraph: 'bg-gray-500',
  list: 'bg-green-500',
  quote: 'bg-amber-500',
  image: 'bg-pink-500',
  video: 'bg-red-500',
  link: 'bg-cyan-500',
  code: 'bg-emerald-500',
  table: 'bg-orange-500',
  divider: 'bg-slate-500',
  canvas: 'bg-rose-500',
  card: 'bg-yellow-500',
  audio: 'bg-fuchsia-500',
};
